###########
### Coc ###
###########

[[plugins]]
repo     = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = 'call init#coc#hook_add()'
# build    = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo     = 'liuchengxu/vista.vim'
depends  = ['coc.nvim', 'lightline.vim']
hook_add = 'call init#vista#hook_add()'

###################
### Dark Powers ###
###################

[[plugins]]
repo  = 'Shougo/dein.vim'

######################
### マルチカーソル ###
######################

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = 'call init#vim_multiple_cursors#hook_add()'

[[plugins]]
repo     = 'osyo-manga/vim-over'
hook_add = 'nnoremap <silent> <Leader>o :OverCommandLine<CR>'

[[plugins]]
repo     = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

########################
### Syntax Highlight ###
########################

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
if has("nvim")
  let g:polyglot_disabled = ['python']
endif
let g:vim_json_syntax_conceal = 0
'''

###########
### Git ###
###########

[[plugins]]
repo = 'tpope/vim-fugitive'

#############
### Filer ###
#############

[[plugins]]
repo     = 'scrooloose/nerdtree.git'
hook_add = 'call init#nerdtree#hook_add()'

####################
### カラーテーマ ###
####################

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'kaicataldo/material.vim'
hook_add = '''
let g:material_terminal_italics = 0
let g:material_theme_style = 'palenight'
'''

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
let g:spring_night_kill_italic = 1
let g:spring_night_high_contrast = 1
'''

##################
### Statusline ###
##################

[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = 'call init#lightline#hook_add()'

#############
### Mics ####
#############

[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo     = 'Yggdroot/indentLine'
hook_add = 'call init#indentLine#hook_add()'

[[plugins]]
repo     = 'andymass/vim-matchup'
hook_add = 'let g:loaded_matchit = 1'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo     = 'junegunn/vim-easy-align'
hook_add = '''
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)
let g:easy_align_ignore_groups = []
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
vnoremap ? :'<,'>TComment<CR>
'''

[[plugins]]
repo = 'previm/previm'
hook_add = '''
if system('uname -a | grep microsoft') != ""
  let g:previm_open_cmd = '/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe'
  let g:previm_wsl_mode = 1
endif
'''

[[plugins]]
repo = 'tyru/open-browser.vim'


[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
command! -bang -nargs=? -complete=dir GFiles call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
let g:fzf_layout = { 'down': '~40%' }
nnoremap <silent> <Leader>f :GFiles<CR>
nnoremap <silent> <Leader>b :Buffers<CR>
nnoremap <silent> <Leader>m :Files<CR>
nnoremap <silent> <Leader>x :Commands<CR>
nnoremap <silent> <Leader>g :Rg<CR>
'''


