###################
### Dark Powers ###
###################

[[plugins]]
repo  = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc'
build = 'make'

######################
### マルチカーソル ###
######################
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo     = 'osyo-manga/vim-over'
hook_add = 'nnoremap <silent> <Leader>o :OverCommandLine<CR>'

[[plugins]]
repo     = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

####################
### 文法チェック ###
####################

[[plugins]]
repo     = 'w0rp/ale'
hook_add = 'call init#ale#hook_add()'

########################
### Syntax Highlight ###
########################
### Protocol Buffer ###
[[plugins]]
repo = 'uarun/vim-protobuf'

### pug ###
[[plugins]]
repo = 'digitaltoad/vim-pug'

### java script ###
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
# repo = 'othree/yajs.vim'

### TypeScript. ###
[[plugins]]
repo = 'leafgarland/typescript-vim'

### Vue ###
[[plugins]]
repo = 'posva/vim-vue'

### JSX ###
[[plugins]]
repo = 'mxw/vim-jsx'

### TOML ###
[[plugins]]
repo = 'cespare/vim-toml'

### yaml ###
[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

### JSON ###
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = 'let g:vim_json_syntax_conceal = 0'

#############
### Mics ####
#############
[[plugins]]
repo = 'deris/vim-shot-f'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'machakann/vim-highlightedyank'


[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_vert_resize = 1
let g:winresizer_horiz_resize = 1
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo     = 'Yggdroot/indentLine'
hook_add = 'call init#indentLine#hook_add()'

[[plugins]]
repo     = 'ryanoasis/vim-devicons'
hook_add = 'call init#vim_devicons#hook_add()'

[[plugins]]
repo     = 'dbakker/vim-projectroot'
hook_add = 'call init#vim_projectroot#hook_add()'

# http://vimcasts.org/episodes/aligning-text-with-tabular-vim/
[[plugins]]
repo = 'godlygeek/tabular'

###########
### Git ###
###########


[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#############
### Filer ###
#############

[[plugins]]
repo     = 'scrooloose/nerdtree.git'
hook_add = 'call init#nerdtree#hook_add()'

####################
### カラーテーマ ###
####################
[[plugins]]
repo = 'hzchirs/vim-material'
hook_add = '''
let g:material_style='palenight'
'''

# [[plugins]]
# repo = 'kaicataldo/material.vim'
# hook_add = '''
# let g:material_theme_style = 'palenight'
# let g:material_terminal_italics = 0
# '''

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = 'let g:spring_night_kill_italic = 1'

##################
### Statusline ###
##################
[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = 'call init#lightline#hook_add()'

[[plugins]]
repo     = 'luochen1990/rainbow'
hook_add = 'call init#rainbow#hook_add()'

[[plugins]]
repo     = 'andymass/vim-matchup'
hook_add = 'let g:loaded_matchit = 1'

# [[plugins]]
# repo = 'kristijanhusak/defx-icons'
# hook_add = 'call init#defx_icons#hook_add()'
#
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# hook_add = 'call init#defx#hook_add()'


