[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
on_map = '<Plug>(git-messenger'
hook_add = '''
let g:git_messenger_include_diff = 'current'
let g:git_messenger_always_into_popup = v:true
let g:git_messenger_into_popup_after_show = v:true
'''


[[plugins]]
on_event = 'BufRead'
repo     = 'junegunn/vim-easy-align'
hook_add = '''
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo     = 'thinca/vim-quickrun'
on_ft    = ['python', 'ruby', 'javascript', 'javascript.jsx', 'typescript']
depends  = ['vimproc']
hook_add = 'call init#vim_quickrun#hook_add()'

[[plugins]]
on_i = 1
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
hook_source = 'call init#neosnippet#hook_source()'

[[plugins]]
repo      = 'Shougo/neomru.vim'

[[plugins]]
repo             = 'Shougo/denite.nvim'
depends          = ['neomru.vim']
on_event         = 'BufRead'
hook_add         = 'call init#denite#hook_add()'
hook_post_source = 'call init#denite#hook_post_source()'

[[plugins]]
repo     = 'mattn/emmet-vim'
on_i     = 1
hook_add = '''
"let g:user_emmet_leader_key='<Space>'
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo             = 'cohama/lexima.vim'
on_i             = 1
hook_add         = 'call init#lexima#hook_add()'
hook_post_source = 'call init#lexima#hook_post_source()'

###########
### Coc ###
###########

[[plugins]]
repo     = 'neoclide/coc.nvim'
on_path  = ['.*']
build    = '''
yarn install
if [ ! -e ~/.config/coc ]; then
    mkdir -p ~/.config/coc
fi
if [ ! -e ~/.config/coc/memos.json ]; then
    echo "{}" > ~/.config/coc/memos.json
fi
'''
hook_add = 'call init#coc#hook_add()'

##########
### GO ###
##########

[[plugins]]
repo     = 'fatih/vim-go'
on_ft    = ['go']
hook_add = 'call init#vim_go#hook_add()'

#############################
### Javascript/TypeScript ###
#############################

[[plugins]]
repo  = 'ruanyl/vim-sort-imports'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo     = 'heavenshell/vim-jsdoc'
on_ft    = ['typescript', 'javascript', 'javascript.jsx']
hook_add = 'call init#vim_jsdoc#hook_add()'

###########
### CSV ###
###########

[[plugins]]
repo  = 'mechatroner/rainbow_csv'
on_ft = ['csv']

###########
### PHP ###
###########

[[plugins]]
repo     = 'jwalton512/vim-blade'
on_ft    = ['blade']
hook_add = 'call init#vim_blade#hook_add()'

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo     = 'tobyS/pdv'
on_ft    = ['php']
depends  = ['vmustache']
hook_add = 'call init#pdv#hook_add()'


#######################
### HTML / Markdown ###
#######################

[[plugins]]
repo     = 'plasticboy/vim-markdown'
on_ft    = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_conceal = 0
let g:vim_markdown_folding_disabled = 1
'''

###############
### Jupyter ###
###############

[[plugins]]
repo     = 'szymonmaszke/vimpyter'
on_ft    = ['ipynb']
hook_add = '''
autocmd Filetype ipynb nmap <silent><C-s>b :VimpyterInsertPythonBlock<CR>
autocmd Filetype ipynb nmap <silent><C-s>j :VimpyterStartJupyter<CR>
autocmd Filetype ipynb nmap <silent><C-s>n :VimpyterStartNteract<CR>
'''

[[plugins]]
repo     = 'liuchengxu/vista.vim'
depends  = ['coc.nvim', 'lightline.vim']
hook_add = 'call init#vista#hook_add()'
