[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
on_map = '<Plug>(git-messenger'
hook_add = '''
nmap <Leader>gm <Plug>(git-messenger)
let g:git_messenger_include_diff = 'current'
let g:git_messenger_always_into_popup = v:true
let g:git_messenger_into_popup_after_show = v:true
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event         = 'BufRead'
hook_source = 'call init#neosnippet#hook_source()'


[[plugins]]
repo     = 'thinca/vim-quickrun'
on_ft    = ['python', 'ruby', 'javascript', 'javascript.jsx', 'typescript']
depends  = ['vimproc']
hook_add = 'call init#vim_quickrun#hook_add()'

[[plugins]]
repo             = 'Shougo/denite.nvim'
depends          = ['neomru.vim']
on_event         = 'BufRead'
hook_add         = 'call init#denite#hook_add()'
hook_post_source = 'call init#denite#hook_post_source()'

[[plugins]]
repo     = 'mattn/emmet-vim'
on_i     = 1
hook_add = '''
"let g:user_emmet_leader_key='<Space>'
'''

##########
### GO ###
##########

[[plugins]]
repo     = 'fatih/vim-go'
on_ft    = ['go']
hook_add = 'call init#vim_go#hook_add()'

# [[plugins]]
# repo = 'zchee/nvim-go'
# build = 'make'
# depends = ['neosnippet.vim']
# on_ft    = ['go']
# hook_add = 'call init#vim_go#hook_add()'

#############################
### Javascript/TypeScript ###
#############################

# [[plugins]]
# repo  = 'ruanyl/vim-sort-imports'
# on_ft = ['javascript', 'typescript']

[[plugins]]
repo     = 'heavenshell/vim-jsdoc'
on_ft    = ['typescript', 'javascript', 'javascript.jsx']
hook_add = 'call init#vim_jsdoc#hook_add()'

###########
### CSV ###
###########

[[plugins]]
repo  = 'mechatroner/rainbow_csv'
on_ft = ['csv']

###########
### PHP ###
###########

[[plugins]]
repo     = 'jwalton512/vim-blade'
on_ft    = ['blade']
hook_add = 'call init#vim_blade#hook_add()'

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo     = 'tobyS/pdv'
on_ft    = ['php']
depends  = ['vmustache']
hook_add = 'call init#pdv#hook_add()'

[[plugins]]
repo = 'numirias/semshi'
on_ft    = ['python']
hook_add = '''
let g:semshi#active = v:true
let g:semshi#error_sign = v:false
let g:semshi#mark_selected_nodes = v:false
let g:semshi#self_to_attribute = v:true
let g:semshi#tolerate_syntax_errors = v:false
'''
#######################
### HTML / Markdown ###
#######################

[[plugins]]
repo     = 'plasticboy/vim-markdown'
on_ft    = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_conceal = 0
let g:vim_markdown_folding_disabled = 1
'''

###############
### Jupyter ###
###############

# [[plugins]]
# repo     = 'szymonmaszke/vimpyter'
# on_ft    = ['ipynb']
# hook_add = '''
# autocmd Filetype ipynb nmap <silent><C-s>b :VimpyterInsertPythonBlock<CR>
# autocmd Filetype ipynb nmap <silent><C-s>j :VimpyterStartJupyter<CR>
# autocmd Filetype ipynb nmap <silent><C-s>n :VimpyterStartNteract<CR>
# '''

[[plugins]]
repo             = 'cohama/lexima.vim'
hook_add         = 'call init#lexima#hook_add()'
on_event         = 'BufRead'
hook_post_source = 'call init#lexima#hook_post_source()'
