##################
### Neosnippet ###
##################

[[plugins]]
on_i = 1
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
hook_source = '''
" Plugin key-mappings.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <expr><TAB>
 \ pumvisible() ? "\<C-n>" :
 \ neosnippet#expandable_or_jumpable() ?
 \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

imap <expr><CR>
\ (pumvisible() && neosnippet#expandable()) ? "\<Plug>(neosnippet_expand_or_jump)" : "\<CR>"


smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
"if has('conceal')
"  set conceallevel=2 concealcursor=niv
"endif
'''

###########
### LSP ###
###########

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_ft = ['vue', 'typescript', 'javascript', 'javascript.jsx', 'ruby']
rev = 'next'
build = 'bash install.sh'
hook_add = '''
set hidden
let s:php_langserver = "vendor/felixfbecker/language-server/bin/php-language-server.php"
let g:LanguageClient_diagnosticsEnable = 0
let g:LanguageClient_serverCommands = {
    \ 'typescript': ['javascript-typescript-stdio'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ 'ruby': ['solargraph', 'stdio'],
"   \ 'php': ['php', s:php_langserver],
    \ 'vue': ['vls'],
    \ }

function! s:langserver_keymap()
    nnoremap <buffer><silent> <F10> :LanguageClientStart<CR>
    nnoremap <buffer><silent> K :call LanguageClient_textDocument_hover()<CR>
    nnoremap <buffer><silent> gd :call LanguageClient_textDocument_definition()<CR>
    nnoremap <buffer><silent> <F2> :call LanguageClient_textDocument_rename()<CR>
endfunction

autocmd FileType ruby :call s:langserver_keymap()
" autocmd FileType php :call s:langserver_keymap()
autocmd FileType typescript :call s:langserver_keymap()
autocmd FileType javascript :call s:langserver_keymap()
autocmd FileType javascript.jsx :call s:langserver_keymap()
autocmd FileType vue :call s:langserver_keymap()
'''

#############################
### Javascript/TypeScript ###
#############################

# jsdoc.vim generates JSDoc block comments based on a function signature.
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = ['typescript', 'javascript', 'javascript.jsx']
hook_add = '''
let g:typescript_compiler_binary = ''
let g:typescript_compiler_options = ''
autocmd FileType javascript :call s:jsdoc_keymap()
autocmd FileType typescript :call s:jsdoc_keymap()
function! s:jsdoc_keymap()
    inoremap <buffer><silent> <C-P> <Esc>:JsDoc<CR>i
    nnoremap <buffer><silent> <C-P> :JsDoc<CR>
    vnoremap <buffer><silent> <C-P> :JsDoc<CR>
endfunction
'''

[[plugins]]
repo = 'ruanyl/vim-sort-imports'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']
hook_add = '''
autocmd User Node
  \ if &filetype == "javascript" || &filetype == "javascript" |
  \   nmap <buffer> <C-w>f <Plug>NodeVSplitGotoFile |
  \   nmap <buffer> <C-w><C-f> <Plug>NodeVSplitGotoFile |
  \ endif
'''

###########
### PHP ###
###########

[[plugins]]
repo = 'jwalton512/vim-blade'
on_ft = ['blade']
hook_add = '''
" Define some single Blade directives. This variable is used for highlighting only.
let g:blade_custom_directives = ['datetime', 'javascript']

" Define pairs of Blade directives. This variable is used for highlighting and indentation.
let g:blade_custom_directives_pairs = {
      \   'markdown': 'endmarkdown',
      \   'cache': 'endcache',
      \ }
'''

[[plugins]]
repo = 'beanworks/vim-phpfmt'
on_ft = ['php']
hook_add = '''
let g:phpfmt_standard = 'PSR2'
let g:phpfmt_autosave = 0
'''

[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'
on_ft = ['php']
hook_add = '''
autocmd FileType php :call s:phpdoc_keymap()
function! s:phpdoc_keymap()
    inoremap <buffer><silent> <C-P> <Esc>:call PhpDocSingle()<CR>i
    nnoremap <buffer><silent> <C-P> :call PhpDocSingle()<CR>
    vnoremap <buffer><silent> <C-P> :call PhpDocSingle()<CR>
endfunction
'''

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = ['php']
build = 'composer install'
hook_add = '''
let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
let g:deoplete#ignore_sources.php = ['omni']
let g:phpcd_autoload_path = './vendor/autoload.php'

function! s:phpcd_keymap()
    silent! nnoremap <silent> <unique> <buffer> gd
        \ :<C-u>call phpcd#JumpToDefinition('normal')<CR>
    silent! nnoremap <silent> <unique> <buffer> <C-W><C-]>
        \ :<C-u>call phpcd#JumpToDefinition('split')<CR>
    silent! nnoremap <silent> <unique> <buffer> <C-W><C-\>
        \ :<C-u>call phpcd#JumpToDefinition('vsplit')<CR>
    silent! nnoremap <silent> <unique> <buffer> <C-t>
        \ :<C-u>call phpcd#JumpBack()<CR>
endfunction
autocmd FileType php :call s:phpcd_keymap()
'''

##########
### GO ###
##########

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
build = '''make '''

##############
### Python ###
##############

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python','python3','djangohtml', 'ipynb']
hook_add = '''
" jediにvimの設定を任せると'completeopt+=preview'するので 自動設定機能をOFFにし手動で設定を行う
" let g:jedi#auto_vim_configuration = 0
" let g:jedi#auto_initialization = 0
" let g:jedi#smart_auto_mappings = 0
let g:jedi#completions_enabled = 0
" 補完の最初の項目が選択された状態だと使いにくいためオフにする
" let g:jedi#popup_select_first = 0
" let g:jedi#popup_on_dot = 1
" let g:jedi#completions_command = '<C-d>'

let g:jedi#documentation_command = 'K'
let g:jedi#rename_command = '<F2>'
let g:jedi#goto_command = 'gd'
let g:jedi#usages_command = '<C-h>'
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3', 'ipynb']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'python3', 'ipynb']

# [[plugins]]
# repo = 'fisadev/vim-isort'
# on_ft = ['python', 'python3', 'djangohtml', 'ipynb']
# hook_add = '''
# let g:vim_isort_map = '<C-i>'
# let g:vim_isort_python_version = 'python3'
# '''

# [[plugins]]
# repo = 'tell-k/vim-autopep8'
# on_ft = ['python', 'python3', 'ipynb']
# hook_add='let g:autopep8_disable_show_diff = 1'

#######################
### HTML / Markdown ###
#######################

[[plugins]]
repo = 'https://github.com/mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']

# [[plugins]]
# repo = 'joker1007/vim-markdown-quote-syntax'
# on_ft = ['markdown','mkd']

# [[plugins]]
# repo = 'kannokanno/previm'
# on_ft = ['markdown','mkd']
#
# [[plugins]]
# repo = 'tyru/open-browser.vim'
# on_ft = ['markdown','mkd']

############
### Ruby ###
############

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

#############
### Scala ###
#############

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

#############
### C/C++ ###
#############

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']
hook_source = '''
if has('unix')
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-4.0/lib/libclang-4.0.so'
    let g:deoplete#sources#clang#clang_header = '/usr/lib/llvm-4.0/include/clang'
    if has('mac')
        let g:deoplete#sources#clang#libclang_path = '/usr/local/opt/llvm/lib/libclang.so'
        let g:deoplete#sources#clang#clang_header = '/usr/local/opt/llvm/include/clang'
    endif
endif
'''

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# depends = ['jedi-vim']
# on_source = ['jedi-vim']
# on_ft = ['python', 'python3']
# hook_post_source= '''
# if jedi#init_python()
#   function! s:jedi_auto_force_py_version() abort
#     let major_version = pyenv#python#get_internal_major_version()
#     call jedi#force_py_version(major_version)
#   endfunction
#   augroup vim-pyenv-custom-augroup
#     autocmd! *
#     autocmd User vim-pyenv-activate-post   call s:jedi_auto_force_py_version()
#     autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
#   augroup END
# endif
# '''

# [[plugins]]
# repo = 'prettier/vim-prettier'
# build = 'npm install'
# on_ft = ['javascript', 'vue', 'typescript', 'css', 'less', 'scss']
# hook_add = '''
# let g:prettier#autoformat = 1
# let g:prettier#quickfix_enabled = 0
# let g:prettier#exec_cmd_async = 1
# autocmd BufWritePre *.js,*.css,*.scss,*.less PrettierAsync
# '''

# [[plugins]]
# repo = 'ternjs/tern_for_vim'
# on_ft = ['javascript']
# build = 'npm i -g tern'
# hook_add = '''
# function! s:js_keymap()
#     nnoremap <buffer><silent> K :TernDoc<CR>
#     nnoremap <buffer><silent> gd :TernDef<CR>
#     nnoremap <buffer><silent> <F2> :TernRename<CR>
#     nnoremap <buffer><silent> <C-h> :TernRefs<CR>
# endfunction
# autocmd FileType javascript :call s:js_keymap()
# '''
#
# [[plugins]]
# repo = 'carlitux/deoplete-ternjs'
# on_ft = ['javascript']
# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# build = 'bash install.sh'
# on_ft = ['javascript', 'typescript']
# hook_add = '''
# let g:nvim_typescript#javascript_support = 1
# let g:nvim_typescript#type_info_on_hold = 1
# let g:nvim_typescript#max_completion_detail = 3
# let g:nvim_typescript#default_signs =
#       \ get(g:, 'nvim_typescript#default_signs', [
#       \{
#       \  'TSinformation': {
#       \   'texthl': 'SpellBad',
#       \   'signText': '•',
#       \   'signTexthl': 'NeomakeInfoSign'
#       \   }
#       \},
#       \{
#       \  'TShint': {
#       \   'texthl': 'SpellBad',
#       \   'signText': '?',
#       \   'signTexthl': 'NeomakeInfoSign'
#       \   }
#       \}
#       \])
# function! s:ts_keymap()
#     nnoremap <buffer><silent> K :TSDoc<CR>
#     nnoremap <buffer><silent> gd :TSDef<CR>
#     nnoremap <buffer><silent> <F2> :TSRename<CR>
#     nnoremap <buffer><silent> <C-h> :TSRefs<CR>
# endfunction
# autocmd FileType typescript :call s:ts_keymap()
# '''
