[[plugins]]
on_event = 'BufRead'
repo     = 'junegunn/vim-easy-align'
hook_add = '''
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo     = 'thinca/vim-quickrun'
on_ft    = ['python', 'ruby', 'javascript', 'javascript.jsx', 'typescript']
depends  = ['vimproc']
hook_add = 'call narona#init#vim_quickrun#hook_add()'

[[plugins]]
on_i = 1
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_i = 1
hook_source = 'call narona#init#neosnippet#hook_source()'

[[plugins]]
repo      = 'Shougo/neomru.vim'

[[plugins]]
repo             = 'Shougo/denite.nvim'
depends          = ['neomru.vim']
on_event         = 'BufRead'
hook_add         = 'call narona#init#denite#hook_add()'
hook_post_source = 'call narona#init#denite#hook_post_source()'

[[plugins]]
repo     = 'mattn/emmet-vim'
on_i     = 1
hook_add = '''
"let g:user_emmet_leader_key='<Space>'
'''

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo             = 'cohama/lexima.vim'
on_i             = 1
hook_add         = 'call narona#init#lexima#hook_add()'
hook_post_source = 'call narona#init#lexima#hook_post_source()'

###########
### Coc ###
###########

[[plugins]]
repo     = 'neoclide/coc.nvim'
on_path  = ['.*']
build    = '''
yarn install
if [ ! -e ~/.config/coc ]; then
    mkdir -p ~/.config/coc
fi
if [ ! -e ~/.config/coc/memos.json ]; then
    echo "{}" > ~/.config/coc/memos.json
fi
'''
hook_add = 'call narona#init#coc#hook_add()'

##########
### GO ###
##########

[[plugins]]
repo     = 'fatih/vim-go'
on_ft    = ['go']
hook_add = 'call narona#init#vim_go#hook_add()'

#############################
### Javascript/TypeScript ###
#############################

[[plugins]]
repo  = 'ruanyl/vim-sort-imports'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo     = 'heavenshell/vim-jsdoc'
on_ft    = ['typescript', 'javascript', 'javascript.jsx']
hook_add = '''
let g:typescript_compiler_binary = ''
let g:typescript_compiler_options = ''
autocmd FileType javascript,typescript :call s:jsdoc_keymap()
function! s:jsdoc_keymap()
    nnoremap <buffer><silent> <Leader>d :JsDoc<CR>
    vnoremap <buffer><silent> <Leader>d :JsDoc<CR>
endfunction
'''

###########
### CSV ###
###########

[[plugins]]
repo  = 'mechatroner/rainbow_csv'
on_ft = ['csv']

###########
### PHP ###
###########

[[plugins]]
repo     = 'jwalton512/vim-blade'
on_ft    = ['blade']
hook_add = '''
" Define some single Blade directives. This variable is used for highlighting only.
let g:blade_custom_directives = ['datetime', 'javascript']

" Define pairs of Blade directives. This variable is used for highlighting and indentation.
let g:blade_custom_directives_pairs = {
      \   'markdown': 'endmarkdown',
      \   'cache': 'endcache',
      \ }
'''

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo     = 'tobyS/pdv'
on_ft    = ['php']
depends  = ['vmustache']
hook_add = '''
let g:pdv_template_dir = $HOME ."/.cache/dein/repos/github.com/tobyS/pdv/templates"
autocmd FileType php :call s:phpdoc_keymap()
function! s:phpdoc_keymap()
    nnoremap <buffer><silent> <Leader>d :call pdv#DocumentCurrentLine()<CR>
    vnoremap <buffer><silent> <Leader>d :call pdv#DocumentCurrentLine()<CR>
endfunction
'''

#######################
### HTML / Markdown ###
#######################

[[plugins]]
repo     = 'plasticboy/vim-markdown'
on_ft    = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_conceal = 0
let g:vim_markdown_folding_disabled = 1
'''

#############
### C/C++ ###
#############

# [[plugins]]
# repo = 'justmao945/vim-clang'
# on_ft = ['c', 'cpp']
#
# [[plugins]]
# repo = 'zchee/deoplete-clang'
# on_ft = ['c', 'cpp', 'cmake']
# depends = ['deoplete.nvim']
# hook_source = '''
# if has('unix')
#     let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-4.0/lib/libclang-4.0.so'
#     let g:deoplete#sources#clang#clang_header = '/usr/lib/llvm-4.0/include/clang'
#     if has('mac')
#         let g:deoplete#sources#clang#libclang_path = '/usr/local/opt/llvm/lib/libclang.so'
#         let g:deoplete#sources#clang#clang_header = '/usr/local/opt/llvm/include/clang'
#     endif
# endif
# '''


###############
### Jupyter ###
###############

[[plugins]]
repo     = 'szymonmaszke/vimpyter'
on_ft    = ['ipynb']
hook_add = '''
autocmd Filetype ipynb nmap <silent><C-s>b :VimpyterInsertPythonBlock<CR>
autocmd Filetype ipynb nmap <silent><C-s>j :VimpyterStartJupyter<CR>
autocmd Filetype ipynb nmap <silent><C-s>n :VimpyterStartNteract<CR>
'''

[[plugins]]
repo     = 'liuchengxu/vista.vim'
depends  = ['coc.nvim', 'lightline.vim']
hook_add = 'call narona#init#vista#hook_add()'
