[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
on_map = '<Plug>(git-messenger'
hook_add = '''
nmap <Leader>gm <Plug>(git-messenger)
let g:git_messenger_include_diff = 'current'
let g:git_messenger_always_into_popup = v:true
let g:git_messenger_into_popup_after_show = v:true
'''

[[plugins]]
repo     = 'mattn/emmet-vim'
on_i     = 1
hook_add = '''
"let g:user_emmet_leader_key='<Space>'
'''

####################
### 文法チェック ###
####################

[[plugins]]
repo     = 'w0rp/ale'
on_ft    = ['go', 'php', 'sh','bash', 'ruby', 'vim']
hook_add = 'call init#ale#hook_add()'


##########
### GO ###
##########

[[plugins]]
repo     = 'fatih/vim-go'
on_ft    = ['go']
hook_add = 'call init#vim_go#hook_add()'

# [[plugins]]
# repo = 'zchee/nvim-go'
# build = 'make'
# depends = ['neosnippet.vim']
# on_ft    = ['go']
# hook_add = 'call init#vim_go#hook_add()'

#############################
### Javascript/TypeScript ###
#############################

[[plugins]]
repo     = 'heavenshell/vim-jsdoc'
on_ft    = ['typescript', 'javascript', 'javascript.jsx']
hook_add = 'call init#vim_jsdoc#hook_add()'

###########
### CSV ###
###########

[[plugins]]
repo  = 'mechatroner/rainbow_csv'
on_ft = ['csv']

###########
### PHP ###
###########

[[plugins]]
repo     = 'jwalton512/vim-blade'
on_ft    = ['blade']
hook_add = 'call init#vim_blade#hook_add()'

[[plugins]]
repo = 'tobyS/vmustache'

[[plugins]]
repo     = 'tobyS/pdv'
on_ft    = ['php']
depends  = ['vmustache']
hook_add = 'call init#pdv#hook_add()'

#######################
### HTML / Markdown ###
#######################

[[plugins]]
repo     = 'plasticboy/vim-markdown'
on_ft    = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_conceal = 0
let g:vim_markdown_folding_disabled = 1
'''
