####################
### 文法チェック ###
####################
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['php','python','python3']
hook_add = '''
let g:ale_linters = {
\   'python': ['autopep8','flake8', 'isort'],
\   'python3': ['autopep8','flake8', 'isort'],
\}
" エラー行に表示するマーク
let g:ale_sign_error = '⨉'
let g:ale_sign_warning = '⚠'
" エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
" エラー表示の列を常時表示
let g:ale_sign_column_always = 0

" ファイルを開いたときにlint実行
let g:ale_lint_on_enter = 1
" ファイルを保存したときにlint実行
let g:ale_lint_on_save = 1
" 編集中のlintはしない
let g:ale_lint_on_text_changed = 'never'

" lint結果をロケーションリストとQuickFixには表示しない
" 出てると結構うざいしQuickFixを書き換えられるのは困る
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_open_list = 0
let g:ale_keep_list_window_open = 0
'''############
### TOML ###
############

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

#######################
### HTML / Markdown ###
#######################
[[plugins]]
repo = 'https://github.com/mattn/emmet-vim'
on_ft = ['html']

#[[plugins]]
#repo = 'plasticboy/vim-markdown'
#on_ft = ['markdown','mkd']

#[[plugins]]
#repo = 'joker1007/vim-markdown-quote-syntax'
#on_ft = ['markdown','mkd']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']

###########
### PHP ###
###########
#[[plugins]]
#repo = 'lvht/phpcd.vim'
#on_ft = ['php']
#build = 'composer install'
#hook_add = '''
#let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
#let g:deoplete#ignore_sources.php = ['omni']
#'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_ft = ['php', 'js', 'json']
rev = 'next'
build = 'bash install.sh'
hook_post_source= '''
set hidden

let g:LanguageClient_serverCommands = {
    \ 'php': ['php-language-server'],
    \ 'json': ['vscode-json-languageservice'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ }

nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> <Leader>d :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <Leader>r :call LanguageClient_textDocument_rename()<CR>
'''


############
### Ruby ###
############
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = ['ruby']

##############
### Python ###
##############
[[plugins]]
repo = 'fisadev/vim-isort'
on_ft = ['python', 'python3', 'djangohtml']
hook_add = '''
let g:vim_isort_map = '<C-i>'
let g:vim_isort_python_version = 'python3'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python','python3','djangohtml']
hook_add = '''
" jediにvimの設定を任せると'completeopt+=preview'するので 自動設定機能をOFFにし手動で設定を行う
" let g:jedi#auto_vim_configuration = 0 
" let g:jedi#auto_initialization = 0
" let g:jedi#smart_auto_mappings = 0 
let g:jedi#completions_enabled = 0
" 補完の最初の項目が選択された状態だと使いにくいためオフにする
" let g:jedi#popup_select_first = 0
" let g:jedi#popup_on_dot = 1
" let g:jedi#completions_command = '<C-d>'

" quickrunと被るため大文字に変更
let g:jedi#rename_command = '<Leader>r'

" gundoと被るため大文字に変更
" let g:jedi#goto_command = '<Leader>d'
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'python3']

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python', 'python3']
hook_add='let g:autopep8_disable_show_diff = 1'

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['jedi-vim']
on_source = ['jedi-vim']
on_ft = ['python', 'python3']
hook_post_source= '''
if jedi#init_python()
  function! s:jedi_auto_force_py_version() abort
    let major_version = pyenv#python#get_internal_major_version()
    call jedi#force_py_version(major_version)
  endfunction
  augroup vim-pyenv-custom-augroup
    autocmd! *
    autocmd User vim-pyenv-activate-post   call s:jedi_auto_force_py_version()
    autocmd User vim-pyenv-deactivate-post call s:jedi_auto_force_py_version()
  augroup END
endif
'''


